name: demo-workflow

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay and generate dragon output
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          cowsay -f dragon "Deploy successful! ðŸ‰" > dragon_output.txt

      - name: Upload dragon_output.txt
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon_output.txt

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon_output.txt
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Show dragon message from file
        run: |
          echo "Here is the dragon message from the file:"
          cat dragon_output.txt

      - name: test
        run: |
          echo "Running tests..."
          echo "Hello"

  list:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: |
          echo "Listing files..."
          ls
