name: demo-workflow

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay

  dragon:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Dragon says Hello
        run: |
          cowsay -f dragon "Deploy successful! ğŸ‰"

  test:
    needs: dragon
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Running tests..."
          echo "Hello"

  list:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: |
          echo "Listing files..."
          ls
